version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 15
  ignore:
  - dependency-name: pillow
    versions:
    - 8.1.1
    - 8.1.2
    - 8.2.0
  - dependency-name: pip-tools
    versions:
    - 6.0.0
    - 6.0.1
